name: Build and test PRs
on:
  pull_request:
    paths:
      - '**'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  build:
    uses: jimmykarily/kairos/.github/workflows/reusable-build-flavor.yaml@1556-pr-one-flavor
    with:
      flavor: ubuntu

  qemu-acceptance-tests:
    uses: jimmykarily/kairos/.github/workflows/reusable-qemu-acceptance-test.yaml@1556-pr-one-flavor
    with:
      flavor: ubuntu
    needs:
      - build
