name: Reusable workflow that builds a specific Kairos flavor

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    permissions:
      id-token: write  # OIDC support
      contents: write
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          ls
